### ISSUE TITLE
D1 - Team Members' Reflection

### ISSUE THREAD

**Issue by jianweiiii** [rawsashimi1604/ICT2106_P2_Project#30]
## Complete Team Members' Reflection

Start Date: 09/02/2023
End Date: 09/02/2023

### Preconditions:
- Finished D1

### Definition of done:

- [x] Christabelle Reflection Done
- [x] Jun Wei Reflection Done
- [x] Gavin Reflection Done
- [x] Edmund Reflection Done
- [x] Nicholas Reflection Done
- [x] Jian Wei Reflection Done

**Comment by Christabellet** [comment]
Reflection Done

![Image](https://user-images.githubusercontent.com/94042374/218017288-0663213a-201f-4c5e-9abf-9f48e47d3e53.png)

**Comment by junweilam** [comment]
Start Date:
End Date:

**Preconditions: **
- None

**Definitions of done: **

- [ ] Christabelle Reflection Done
- [ ] Jun Wei Reflection Done
- [ ] Gavin Reflection Done
- [ ] Edmund Reflection Done
- [ ] Nicholas Reflection Done
- [ ] Jian Wei Reflection Done

**Comment by 2102673** [comment]
Gavin Loo Wei Ren
Through this project, I have realised what a mammoth of a task software development is. Working with over 40 students for this project definitely was tough but on the other hand was an enriching experience for me. It provided me with valuable insight of how working in the real world is to be, and how to communicate effectively to deliver a successful product. Additionally, being a team leader, I managed to learn how to liaise with the different teams, to negotiate boundaries around the different components as well as delegate work to my teammates. I have also learnt different enterprise software design patterns and understood good software design principles such as cohesion, coupling and modularisation. This was really put into good practice when designing the modules as a lab group. Lastly, I gained good experience in modern frameworks such as .NET, REACT, as well as practiced on my SQL skills. This will definitely help me in my IWSP where I can put these skills to use on industry projects. Definitely I would start on things sooner if possible so that the project would be less stressful towards the deadline.


Edmund Lee
In this project, it was lost when the project specification was out. Luckily, we have many good leaders. With them coming together and coming out with the overall structure of the desired program make all lost sheep get back on track. 
Doing this project is like putting us into the real-world environment but with guidance. I also thought that it is an easy task to code and integrate everyone code together without fail. After going through this, I realized that it was not that easy. We need to plan many things. The architecture we are going to use, the software design, and how each module is going to communicate with each other.  Overall, I hope that I am able to complete my assigned task on time, and hope that the whole class can deliver a complete and outstanding SmartHomeManager Web Application to be the second class to break the history.


Quek Kai Jie Nicholas
Through this project, I have realized that it is important to thoroughly understand the problem that the software is intended to solve, and to identify the specific requirements and constraints of the project. I also learned that software should be designed with the end-user in mind, and the design should be based on a deep understanding of the user's needs, goals, and behaviors Also, the software design should use abstraction and encapsulation to reduce complexity and increase readability, making it easier for us to understand and maintain the code. I am glad the team communication is good and there wasn’t any issue. If I could do something differently it would be to start doing the project at an earlier date as a lot of projects were due near/on the same day. 


Lim Jian Wei
Being a first timer in such a big project, what I found out was teamwork and communication was crucial for this project. As the project is progresses, i have to learn new framework such as ASP .NET core, C#, React and Chakra UI to align with the whole team. This gave me an eye opening as it is a different type of project compared to what I have done. I also have a great time learning how to deal with real life clients and how to gather requirements with only 1 meeting with clients. By making sure the team component is loosely coupled with high cohesion, this improves the software design and maintainability. If I could do something differently, I will look into more of ASP .NET core as it is an important framework to build modern web applications due to its cross-platform capabilities, high performance, open-source nature, modular design, and integration with other technologies.


Lam Jun Wei 
Through this software design project, I have gained experience working in a big team where communication is key to being able to complete the tasks without much conflicts. While working on the project, I am also able to learn new languages or frameworks that I have never tried before like chakra-ui and ASP.net. I am glad that the team communicates and collaborates well hence the progress of the project so far is looking good. If i could do something differently it would be reading up more on what is needed for the project before starting.
